Abort if current branch is develop, master or main

diff --git a/mdd b/mdd
--- a/mdd
+++ b/mdd
@@ -4,8 +4,12 @@
 
 BRANCH=$(git branch --show-current)
 
+if [ "$BRANCH" == "develop" ] || [ "$BRANCH" == 'master' ] || [ "$BRANCH" == 'main' ]; then
+    echo "You are on branch \"$BRANCH\", aborting!" >&2
+    exit 1;
+fi;
+
 git checkout develop && \
 git merge "$BRANCH" && \
 git branch -d "$BRANCH" && \
 git push
-
